apiVersion: v1
kind: Secret
metadata:
  name: azure-keyvault-config
  namespace: supacrypt
  labels:
    app: supacrypt-backend
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  vault-uri: ""  # echo -n "https://your-vault.vault.azure.net/" | base64